version: '3.8'

services:
  web:
    build: .
    container_name: django_app
    command: sh -c "sleep 15 && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    environment:
      MYSQL_DATABASE: figsac
      MYSQL_USER: admin
      MYSQL_PASSWORD: C6!~g(nAk?qR
      MYSQL_HOST: database-1.c9q8q0m0uoth.us-east-2.rds.amazonaws.com  # Pones aqu√≠ tu endpoint de RDS
      MYSQL_PORT: 3306
